#! /usr/bin/env python

import os

Import([ "env" ])

obj = env.Object(env.Glob("*.cc"))

obj.extend(SConscript(os.path.join("audio", "SConscript"), exports=[ "env" ]))
obj.extend(SConscript(os.path.join("gui", "SConscript"), exports=[ "env" ]))
obj.extend(SConscript(os.path.join("renderer", "SConscript"), exports=[ "env" ]))
obj.extend(SConscript(os.path.join("scene", "SConscript"), exports=[ "env" ]))
obj.extend(SConscript(os.path.join("ui", "SConscript"), exports=[ "env" ]))

Return("obj")
