#if !defined __CONTROLS_H__
#define __CONTROLS_H__

enum Controls
{
    ID_VIEW_FULLSCREEN = 1000,

    ID_EDITOR_RESOURCES = 2000,
    ID_EDITOR_RENDER_BOUNDS = 2001,
    ID_EDITOR_RENDER_WIREFRAME = 2002,
    ID_EDITOR_RENDER_SHADOWS = 2003,
    ID_EDITOR_RENDER_SKELETON = 2004,
    ID_EDITOR_ENABLE_LIGHTING = 2005,
    ID_EDITOR_RENDER_NORMALS = 2006,

    ID_EDITOR_RENDER_BUMP = 2100,
    ID_EDITOR_RENDER_VERTEX = 2101,

    ID_DEBUG_MEMORY = 3000,
    ID_DEBUG_ROTATE_ACTORS = 3001
};

#endif
